use std::io::{Read, Write};
use std::net::{
    IpAddr, Ipv4Addr, Ipv6Addr, Shutdown, SocketAddr, SocketAddrV4, TcpListener, TcpStream,
    UdpSocket,
};
use std::sync::mpsc;
use std::thread;

use super::forwarder::{forward_udp_query, relay_bidirectional};
use super::plan::{
    build_inherited_dns_config, prepare_rootless_dns_plan, render_gateway_resolv_conf,
};

fn tcp_pair() -> (TcpStream, TcpStream) {
    let listener = TcpListener::bind(SocketAddrV4::new(Ipv4Addr::LOCALHOST, 0)).unwrap();
    let addr = listener.local_addr().unwrap();
    let (tx, rx) = mpsc::channel();

    let join = thread::spawn(move || {
        let accepted = listener.accept().unwrap().0;
        tx.send(accepted).unwrap();
    });

    let client = TcpStream::connect(addr).unwrap();
    let server = rx.recv().unwrap();
    join.join().unwrap();

    (client, server)
}

#[test]
fn forward_udp_query_relays_response_from_upstream() {
    let upstream = UdpSocket::bind(SocketAddrV4::new(Ipv4Addr::LOCALHOST, 0)).unwrap();
    let upstream_addr = match upstream.local_addr().unwrap() {
        SocketAddr::V4(addr) => addr,
        SocketAddr::V6(_) => panic!("expected an IPv4 upstream socket"),
    };

    let expected_query = b"\x12\x34dns-query".to_vec();
    let expected_response = b"\x12\x34dns-response".to_vec();

    let join = thread::spawn({
        let expected_query = expected_query.clone();
        let expected_response = expected_response.clone();
        move || {
            let mut buf = [0_u8; 64];
            let (n, peer) = upstream.recv_from(&mut buf).unwrap();
            assert_eq!(&buf[..n], expected_query.as_slice());
            upstream.send_to(&expected_response, peer).unwrap();
        }
    });

    let actual = forward_udp_query(&expected_query, SocketAddr::V4(upstream_addr)).unwrap();
    join.join().unwrap();

    assert_eq!(actual, expected_response);
}

#[test]
fn relay_bidirectional_copies_data_in_both_directions() {
    let (mut left_peer, mut left_relay) = tcp_pair();
    let (mut right_peer, mut right_relay) = tcp_pair();

    let request = b"dns request payload".to_vec();
    let response = b"dns response payload".to_vec();

    let upstream_join = thread::spawn({
        let request = request.clone();
        let response = response.clone();
        move || {
            let mut received = vec![0_u8; request.len()];
            right_peer.read_exact(&mut received).unwrap();
            assert_eq!(received, request);

            right_peer.write_all(&response).unwrap();
            right_peer.shutdown(Shutdown::Write).unwrap();
        }
    });

    left_peer.write_all(&request).unwrap();
    left_peer.shutdown(Shutdown::Write).unwrap();

    relay_bidirectional(&mut left_relay, &mut right_relay).unwrap();
    upstream_join.join().unwrap();

    let mut received = Vec::new();
    left_peer.read_to_end(&mut received).unwrap();
    assert_eq!(received, response);
}

#[test]
fn build_inherited_dns_config_rewrites_nameserver_and_preserves_options() {
    let host_resolv = "\
# Generated by test
nameserver 8.8.8.8
search example.internal
options edns0 trust-ad
";

    let config = build_inherited_dns_config(
        host_resolv,
        Ipv4Addr::new(10, 0, 0, 2),
        Ipv6Addr::new(0xfd42, 0, 0, 0, 0, 0, 0, 2),
    )
    .unwrap();

    assert_eq!(config.upstream, IpAddr::V4(Ipv4Addr::new(8, 8, 8, 8)));
    assert_eq!(
        config.resolv_conf,
        "search example.internal\noptions edns0 trust-ad\nnameserver 10.0.0.2\nnameserver fd42::2\n"
    );
}

#[test]
fn build_inherited_dns_config_adds_default_options_when_missing() {
    let host_resolv = "\
nameserver 2001:4860:4860::8888
domain example.internal
nameserver 1.1.1.1
";

    let config = build_inherited_dns_config(
        host_resolv,
        Ipv4Addr::new(172, 16, 0, 10),
        Ipv6Addr::new(0xfd42, 0x1234, 0x5678, 0, 0, 0, 0, 10),
    )
    .unwrap();

    assert_eq!(
        config.upstream,
        IpAddr::V6("2001:4860:4860::8888".parse().unwrap())
    );
    assert_eq!(
        config.resolv_conf,
        "domain example.internal\nnameserver 172.16.0.10\nnameserver fd42:1234:5678::a\noptions timeout:1 attempts:1\n"
    );
}

#[test]
fn build_inherited_dns_config_rejects_missing_nameserver() {
    let host_resolv = "search example.internal\n";

    let err = build_inherited_dns_config(
        host_resolv,
        Ipv4Addr::new(10, 0, 0, 2),
        Ipv6Addr::new(0xfd42, 0, 0, 0, 0, 0, 0, 2),
    )
    .unwrap_err();
    assert!(err.to_string().contains("no usable nameserver found"));
}

#[test]
fn render_gateway_resolv_conf_adds_default_options_for_explicit_rootless_dns() {
    let rendered = render_gateway_resolv_conf(
        &[],
        Ipv4Addr::new(10, 240, 1, 1),
        "fd42::1".parse().unwrap(),
        true,
    );

    assert_eq!(
        rendered,
        "nameserver 10.240.1.1\nnameserver fd42::1\noptions timeout:1 attempts:1\n"
    );
}

#[test]
fn prepare_rootless_dns_plan_points_child_to_gateway_and_keeps_upstream() {
    let run_id = format!("unit-test-{}", std::process::id());
    let plan = prepare_rootless_dns_plan(
        &run_id,
        Some("1.1.1.1".parse().unwrap()),
        Ipv4Addr::new(10, 240, 1, 1),
        "fd42::1".parse().unwrap(),
    )
    .unwrap();

    assert_eq!(plan.rootful_upstream, None);
    assert_eq!(plan.rootless_upstream(), Some("1.1.1.1".parse().unwrap()));

    let path = plan.resolv_conf_path().unwrap();
    let content = std::fs::read_to_string(path).unwrap();
    assert_eq!(
        content,
        "nameserver 10.240.1.1\nnameserver fd42::1\noptions timeout:1 attempts:1\n"
    );
}
